apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  template:
    spec:
      containers:
      - name: the-container
        resources:
          limits:
            memory: 512Mi
